name       : i3-style
version    : 1.0.2
release    : 3
source     :
    - https://github.com/acrisci/i3-style/archive/v1.0.2.tar.gz : 44934a39094e43f541ffa2416c9f76cc400228c6104ae6b8f0df17e061af1a7b
license    : BSD-2-Clause
component  : desktop.i3
networking : yes
summary    : Make your i3 config a little more stylish.
description: |
    Make your i3 config a little more stylish.
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -dm00644 $installdir/usr/bin
    install -Dm00755 $workdir/target/release/i3-style $installdir/usr/bin/i3-style
