name       : i3-style
version    : 0.10.0
release    : 1
source     :
    - https://github.com/acrisci/i3-style/archive/v0.10.0.tar.gz : e052063abe7a07f24bdc93e3aa18ff93b81282093b4641cfb245ba3b74baddf3
license    : BSD-2-Clause
component  : desktop.i3
networking : yes
summary    : Make your i3 config a little more stylish.
description: |
    Make your i3 config a little more stylish.
builddeps  :
    - nodejs
setup      : |
    npm install
build      : |
    export PATH=$PATH:$workdir/node_modules/coffee-script/bin/
    cake build
install    : |
    install -dm00644 $installdir/usr/bin
    install -dm00644 $installdir/usr/lib/node_modules/i3-style
    cp -R lib node_modules themes package.json $installdir/usr/lib/node_modules/i3-style/
    ln -s /usr/lib/node_modules/i3-style/lib/cli.js $installdir/usr/bin/i3-style
